In [1]:
import pandas as pd

In [11]:
df2015=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\order_2015.csv')
df2016=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\order_2016.csv')
df2017=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\order_2017.csv')
df2018=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\order_2018.csv')

In [3]:
df2015.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ES-2015-2801336,42157,42161,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,South,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88
1,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25
2,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44
3,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49
4,ES-2015-5235241,42243,42244,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,Central,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62

In [4]:
orders=pd.concat([df2015,df2016,df2017,df2018])

In [5]:
orders.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ES-2015-2801336,42157,42161,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,South,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88
1,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25
2,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44
3,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49
4,ES-2015-5235241,42243,42244,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,Central,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62

In [12]:
(orders.isnull()).sum()

order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
city             0
state            0
country          0
region           0
product_id       0
category         0
sub_category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64

In [13]:
orders.describe()

         order_date     ship_date         sales      discount        profit
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean   42869.629000  42873.635000    293.808906      0.103105     37.282974
std      411.746281    411.766159    486.055635      0.174782    178.100384
min    42005.000000  42009.000000      2.955000      0.000000  -3059.820000
25%    42551.000000  42556.000000     49.462500      0.000000      1.320000
50%    42925.000000  42927.000000    119.355000      0.000000     14.220000
75%    43254.000000  43257.000000    320.708625      0.100000     48.510000
max    43465.000000  43470.000000   7958.580000      0.850000   3979.080000

In [14]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 3527
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10000 non-null  object
 1   order_date     10000 non-null  int64
 2   ship_date      10000 non-null  int64
 3   ship_mode      10000 non-null  object
 4   customer_id    10000 non-null  object
 5   customer_name  10000 non-null  object
 6   segment        10000 non-null  object
 7   city           10000 non-null  object
 8   state          10000 non-null  object
 9   country        10000 non-null  object
 10  region         10000 non-null  object
 11  product_id     10000 non-null  object
 12  category       10000 non-null  object
 13  sub_category   10000 non-null  object
 14  product_name   10000 non-null  object
 15  sales          10000 non-null  float64
 16  quantity       10000 non-null  object
 17  discount       10000 non-null  float64
 18  profit         10000 non-null  float64
dtypes: float64(3), int64(2), object(14)
memory usage: 1.5+ MB

In [15]:
orders=orders.rename(columns={'Order ID':'order_id','Order Date':'order_date','Ship Date':'ship_date','Ship Mode':'ship_mode','Customer ID':'customer_id',
                     'Segment':'segment','City':'city','State':'state','Country':'country','Region':'region','Product ID':'product_id','Category':'category',
                     'Sub-Category':'sub_category','Product Name':'product_name','Sales':'sales','Quantity':'quantity','Discount':'discount','Profit':'profit',
                             'Customer Name':'customer_name'})

In [16]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,ES-2015-2801336,42157,42161,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,South,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88
1,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25
2,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44
3,ES-2015-3186072,42275,42279,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,North,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49
4,ES-2015-5235241,42243,42244,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,Central,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62

In [17]:
orders['order_date'] = pd.to_datetime(
    orders['order_date'],
    unit='D',
    origin='1899-12-30'
)

orders['ship_date'] = pd.to_datetime(
    orders['ship_date'],
    unit='D',
    origin='1899-12-30'
)

In [31]:
map_data={'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10}
orders['quantity']=orders['quantity'].replace(map_data)

In [32]:
orders['quantity']=pd.to_numeric(orders['quantity'])

In [33]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 3527
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10000 non-null  object
 1   order_date     10000 non-null  datetime64[ns]
 2   ship_date      10000 non-null  datetime64[ns]
 3   ship_mode      10000 non-null  object
 4   customer_id    10000 non-null  object
 5   customer_name  10000 non-null  object
 6   segment        10000 non-null  object
 7   city           10000 non-null  object
 8   state          10000 non-null  object
 9   country        10000 non-null  object
 10  region         10000 non-null  object
 11  product_id     10000 non-null  object
 12  category       10000 non-null  object
 13  sub_category   10000 non-null  object
 14  product_name   10000 non-null  object
 15  sales          10000 non-null  float64
 16  quantity       10000 non-null  int64
 17  discount       10000 non-null  float64
 18  profit         10000 non-null  float64
 19  year           10000 non-null  int32
 20  delivery_days  10000 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(3), int32(1), int64(1), object(13), timedelta64[ns](1)
memory usage: 1.6+ MB

In [34]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,year,delivery_days
0,ES-2015-2801336,2015-06-02,2015-06-06,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,...,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88,2015,4 days
1,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25,2015,4 days
2,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44,2015,4 days
3,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49,2015,4 days
4,ES-2015-5235241,2015-08-27,2015-08-28,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,...,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62,2015,1 days

In [35]:
orders[['order_date','ship_date']].head()

  order_date  ship_date
0 2015-06-02 2015-06-06
1 2015-09-28 2015-10-02
2 2015-09-28 2015-10-02
3 2015-09-28 2015-10-02
4 2015-08-27 2015-08-28

In [36]:
orders['year']=orders['order_date'].dt.year

In [37]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,year,delivery_days
0,ES-2015-2801336,2015-06-02,2015-06-06,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,...,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88,2015,4 days
1,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25,2015,4 days
2,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44,2015,4 days
3,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49,2015,4 days
4,ES-2015-5235241,2015-08-27,2015-08-28,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,...,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62,2015,1 days

In [38]:
orders['delivery_days']=orders['ship_date']-orders['order_date']

In [39]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,year,delivery_days
0,ES-2015-2801336,2015-06-02,2015-06-06,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,...,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88,2015,4 days
1,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25,2015,4 days
2,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44,2015,4 days
3,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49,2015,4 days
4,ES-2015-5235241,2015-08-27,2015-08-28,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,...,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62,2015,1 days

In [40]:
orders['year'].value_counts()

year
2018    3528
2017    2577
2016    2242
2015    1653
Name: count, dtype: int64

In [41]:
orders['category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [42]:
orders['region'].unique()

array(['South', 'North', 'Central'], dtype=object)

In [43]:
people=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\People.csv')
returns=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\Returns.csv')
target=pd.read_csv(r'C:\my_da_projects\assignment_1st_round\Target.csv')

In [53]:
people.head()

    region            people
0    North  Ross DeVincentis
1    South   Damala Kotsonis
2  Central       Emily Burns

In [54]:
returns.head()

          order_id returned
0  ES-2015-1137137      Yes
1  ES-2015-1141056      Yes
2  ES-2015-1228490      Yes
3  ES-2015-1228490      Yes
4  ES-2015-1228490      Yes

In [55]:
target.head()

          category  year sales_target
0  Office Supplies  2015         170K
1       Technology  2015         180K
2        Furniture  2015         190K
3  Office Supplies  2016         190K
4       Technology  2016         180K

In [56]:
people=people.rename(columns={'Region':'region','People':'people'})

In [57]:
returns=returns.rename(columns={'Order ID':'order_id','Returned':'returned'})

In [58]:
target=target.rename(columns={'Category':'category','Year':'year','Sales Target':'sales_target'})

In [59]:
target.head()

          category  year sales_target
0  Office Supplies  2015         170K
1       Technology  2015         180K
2        Furniture  2015         190K
3  Office Supplies  2016         190K
4       Technology  2016         180K

In [61]:
people.head()

    region            people
0    North  Ross DeVincentis
1    South   Damala Kotsonis
2  Central       Emily Burns

In [62]:
returns.head()

          order_id returned
0  ES-2015-1137137      Yes
1  ES-2015-1141056      Yes
2  ES-2015-1228490      Yes
3  ES-2015-1228490      Yes
4  ES-2015-1228490      Yes

In [52]:
orders.to_csv('orders_cleaned.csv',index=False)

In [63]:
people.to_csv('people_cleaned.csv',index=False)
returns.to_csv('returns_cleaned.csv',index=False)
target.to_csv('target_cleaned.csv',index=False)

In [64]:
import os

In [65]:
os.getcwd()

'C:\\Users\\Home'

In [18]:
orders[orders['order_id'] == 'ES-2016-5371207']

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
2238,ES-2016-5371207,2016-01-25,2016-01-29,Standard Class,GB-14575,Giulietta Baptist,Consumer,Hamburg,Hamburg,Germany,Central,OFF-BI-10002083,Office Supplies,Binders,"Acco Hole Reinforcements, Economy",6.66,one,0.0,0.57
2239,ES-2016-5371207,2016-01-25,2016-01-29,Standard Class,GB-14575,Giulietta Baptist,Consumer,Hamburg,Hamburg,Germany,Central,OFF-SU-10003211,Office Supplies,Supplies,"Acme Ruler, Steel",96.66,six,0.0,28.98
2240,ES-2016-5371207,2016-01-25,2016-01-29,Standard Class,GB-14575,Giulietta Baptist,Consumer,Hamburg,Hamburg,Germany,Central,TEC-PH-10001664,Technology,Phones,"Motorola Office Telephone, VoIP",502.95,7,0.0,221.13
2241,ES-2016-5371207,2016-01-25,2016-01-29,Standard Class,GB-14575,Giulietta Baptist,Consumer,Hamburg,Hamburg,Germany,Central,OFF-AR-10001228,Office Supplies,Art,"Stanley Markers, Water Color",152.28,6,0.0,50.22

In [30]:
orders.iloc[[-1]]

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,country,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,year,delivery_days
3527,IT-2018-5726048,2018-11-24,2018-11-27,Second Class,DK-12985,Darren Koutras,Consumer,Dublin,Dublin,Ireland,...,OFF-AR-10000715,Office Supplies,Art,"Boston Markers, Blue",26.37,2,0.5,-4.77,2018,3 days

In [60]:
returns.head()

          order_id returned
0  ES-2015-1137137      Yes
1  ES-2015-1141056      Yes
2  ES-2015-1228490      Yes
3  ES-2015-1228490      Yes
4  ES-2015-1228490      Yes